namespace Qowaiv.CodeGeneration.Syntax;

public sealed class AutoGeneratedHeader : Code
{
    /// <inheritdoc />
    public void WriteTo(CSharpWriter writer) => Guard.NotNull(writer)
        .Line("// ------------------------------------------------------------------------------")
        .Line("// <auto-generated>")
        .Line("//     This code was generated by a tool.")
        .Line("//")
        .Line("//     Changes to this file may cause incorrect behavior and will be lost if")
        .Line("//     the code is regenerated.")
        .Line("// </auto-generated>")
        .Line("// ------------------------------------------------------------------------------")
        .Line();
}
