using Qowaiv.CodeGeneration.Syntax;

namespace Syntax.Auto_generated_header_specs;

public class Content
{
    [Test]
    public void with_auto_generated_tag()
        => Headers.AutoGenerated().Should().HaveContent(
           @"// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     - Qowaiv.CodeGeneration       *
//     - Qowaiv.CodeGeneration.Specs 1.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

");
}
